// Generated by 'unplugin-auto-import'
// We suggest you to commit this file into source control
declare global {
  const ElOption: typeof import('element-plus/es')['ElOption'];
  const ElRadio: typeof import('element-plus/es')['ElRadio'];
  const ElSelect: typeof import('element-plus/es')['ElSelect'];
}
export {};
